### ISSUE TITLE
[CRASH CAUSED BY PRISON MAP / SCRIPT]

### ISSUE THREAD

**Issue by SirOMGitsYOU** [TayMcKenzieNZ/Ranch-De-Caniche#5]
this causes my game to crash when using the files to not generate the automatic spawning heli or vehicles

**Comment by SirOMGitsYOU** [comment]
EDIT: just tried with original files and same issue occurs, seems to only be when loading the area
[CfxCrashDump_2022_01_10_16_24_51.zip](https://github.com/TayMcKenzieNZ/Ranch-De-Caniche/files/7840303/CfxCrashDump_2022_01_10_16_24_51.zip)

**Comment by TayMcKenzieNZ** [comment]
If you have a prison map or script, this seems to conflict.

**Comment by SirOMGitsYOU** [comment]
> If you have a prison map or script, this seems to conflict.

Ah I do have a prison map, do you know any prison maps that don't conflict?

**Comment by TayMcKenzieNZ** [comment]
I don't know of any, sorry, however your crash sounds very similar to these comments by FiveM community member Pole_Ice;

"I only first discovered this on the version before this one, so the last two versions its happening for me.

I tested it further, I also crash if I try cutting into the pumpkin patch or going around the back closer to the highway near the fence… anytime I try to run to the helicopter from the north side, I always crash.

I’ve found the resource causing this crash, its GitHub - qbcore-framework/prison_map: Maps Used With QB-Prison 5

More specifically the Prisonmainblock. I’ve opened an issue on the github to notify qbcore-framework about it."

You can see that issue here:

https://github.com/qbcore-framework/prison_map/issues/1

**Comment by SirOMGitsYOU** [comment]
> qbcore-framework/prison_map#1

thanks I'll take a look and see if I can remove it and experience the crash

**Comment by TayMcKenzieNZ** [comment]
Apparently removing it stops the crash.

**Comment by SirOMGitsYOU** [comment]
Thanks I’ve changed to using the UncleJust prison MLO and it’s fixed the issue I was having!

**Comment by TayMcKenzieNZ** [comment]
Nice! If you want to check out the custom scenario I made for the ranch, I have a resource for that too, but I had to edit other scenario files to remove peds standing in the streets relating to SP triathlons etc 😄
